# 欢迎使用 Jekyll！
#
# 本配置文件用于那些会影响整个站点的设置，这些值通常只需在建立站点时设置一次，
# 之后基本不需要再改动。
# 出于技术原因，使用 `jekyll serve -l -H localhost` 时该文件 *不会* 被自动重新加载。
# 如果你修改了此文件，请重启服务器进程。

# 基础站点设置
locale                   : "en-US"
site_theme               : "default"
title                    : "Yizhuo Lv"
title_separator          : "-"
name                     : &name "Homepage of Yizhuo Lv"
description              : &description "Lv Yizhuo's academic personal website focuses on research in machine learning and data mining."
url                      : https://Lvyizhuo.github.io # 站点的主机名与协议，例如 "https://[你的 GitHub 用户名].github.io"，如果站点的其他页面托管在 GitHub 上，则设为 "https://[你的 GitHub 用户名].github.io/[你的仓库名]"
baseurl                  : "" # 站点的子路径，例如 "/blog"
repository               : "Lvyizhuo/Lvyizhuo.github.io"

# 站点作者 - 下面的设置控制侧边栏中作者信息所展示的内容。
#               如果某一字段为空，则对应的图标和链接不会显示；否则将显示。
#               进一步的自定义可通过编辑 /_includes/author-profile.html 完成
author:
  # 个人基本信息
  avatar           : "profile.png"
  name             : "吕一卓 Yizhuo Lv 🏄🏻‍♀"
  pronouns         : # 示例： "she/her"
  bio              : "He is currently pursuing a master's degree. His research interests include machine learning and data mining."
  location         : "Jinan, China"
  employer         : "Qilu University of Technology"
  uri              : # URL
  email            : "lvonezhuo@163.com"

  # 学术网站
  academia         : # URL
  arxiv            : # URL - 请更新为你个人主页的正确链接
  googlescholar    : "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  impactstory      : # URL
  orcid            : "http://orcid.org/0009-0009-4235-5209"
  semantic         : # URL
  # pubmed           : "https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"
  researchgate     : # URL
  scopus           : # URL

  # 仓库与软件开发
  bitbucket        : # 用户名 - 请更新为你在该站点上的用户名
  codepen          : # 用户名
  dribbble         : # 用户名
  github           : "Lvyizhuo"
  kaggle           : # 用户名
  stackoverflow    : # 用户编号（或 用户编号和用户名，如 "1" 或 "1/jeff-atwood"）

  # 社交媒体
  bluesky          : #"bsky.app" # 替换为你的 Bluesky 用户名
  facebook         : # 用户名
  flickr           : # 用户名
  foursquare       : # 用户名
  goodreads        : # 用户名
  google_plus      : # 用户名
  keybase          : # 用户名
  instagram        : # 用户名
  lastfm           : # 用户名
  linkedin         : # 用户名
  mastodon         : # URL
  medium           : # URL
  pinterest        : # 用户名
  soundcloud       : # 用户名
  steam            : # 用户名
  telegram         : # URL
  tumblr           : # 用户名
  twitter          : mmgg04
  vine             : # 用户名
  weibo            : # 用户名s
  wikipedia        : # 用户名
  xing             : # 用户名
  youtube          : # 用户名
  zhihu            : # 用户名

# 站点设置
teaser                   :  # 后备导语图片的文件名，放在 /images/ 目录下，例如 "500x300.png"
breadcrumbs              : false # true, false（默认）
words_per_minute         : 160
future                   : true
read_more                : "disabled" # 若启用，则为摘要添加“阅读更多”链接
comments:
  provider               : # false（默认）, "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname            :
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 ，例如：meta.discourse.org
  facebook:
    appid                :
    num_posts            : # 5（默认）
    colorscheme          : # "light"（默认）, "dark"
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages" # "master", "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" # "iso8601"（默认）, "timestamp-seconds", "timestamp-milliseconds"
atom_feed:
  hide                   : false     # 改为 true 可隐藏页脚中的 RSS 订阅
  path                   : # 留空（默认）使用 feed.xml


# SEO（搜索引擎优化）相关
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :


# 社交分享
twitter:
  username               : &twitter “@mmgg04”
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :  # Open Graph/Twitter 默认站点图片
# 用于指定社交资料
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person 或 Organization（默认为 Person）
  name                   : # 如果用户或组织名称与站点名称不同，可在此填写
  links: # 社交主页链接的数组


# 统计分析
analytics:
  provider               :  "false" # false（默认）, "google", "google-universal", "google-analytics-4", "custom"
  google:
    tracking_id          :


# 读取文件
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# 转换设置
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown 处理
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# 集合目前已不使用（所有内容都合并到了主页上）


# 以下设置控制页面与集合如何被包含到站点中
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # 集合默认值已移除 —— 所有内容合并到主页


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# 输出设置
permalink: /:categories/:title/
# paginate: 5 # 每页展示的文章数量
# paginate_path: /page:num/
timezone: Etc/UTC # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# 插件
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# 在 --safe 模式下模拟 GitHub Pages
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji


# 归档
#  类型（Type）
#  - 使用 Liquid 构建、兼容 GitHub Pages 的归档页面 ~> type: liquid（默认）
#  - 使用 Jekyll Archives 插件构建的归档页面 ~> type: jekyll-archives
#  路径（Path，示例）
#  - 使用 Liquid 方法时，归档页面应当存在于相应路径下，否则可能出现失效链接
#    （尤其是启用了面包屑导航时）
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/archives/category-name/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML 压缩
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
