title: Yizhuo Lv's Homepage
page-top-title: Yizhuo Lv
top-section-bg-text: Welcome to Yizhuo's homepage
home-subtitle: Yizhuo Lv&ensp;|&ensp;吕一卓
copyright-text: '&copy; Yizhuo Lv 2024-2027. All Rights Reserved.'